app/models/auth.py
from app.extensions import db

class Auth(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), nullable=False)
    user = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(180), nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    password_hint = db.Column(db.String(100))
    photo = db.Column(db.String(180), unique=False, nullable=False, default='profile.jpg')

    def __repr__(self):
        return f'<Auth {self.username}>'

app/models/bike.py
from app.extensions import db

class Bike(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    owner = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.String(20), unique=True, nullable=False)
    model = db.Column(db.Integer, default=0, nullable=False)
    wheel = db.Column(db.Integer, default=0, nullable=False)
    iron = db.Column(db.Integer, default=0, nullable=False)
    color = db.Column(db.Text, nullable=False)
    
    owner = db.Column(db.Integer, db.ForeignKey('client.id', ondelete='CASCADE'), nullable=False)
    
    def __repr__(self):
        return f'<Bike {self.id}>, Owner {self.owner}'

app/models/client.py
from app.extensions import db

class Client(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    cellphone = db.Column(db.String(20))
    telephone = db.Column(db.String(20))
    cep = db.Column(db.String(10))
    street = db.Column(db.String(100))
    number = db.Column(db.String(10))
    complement = db.Column(db.String(100))
    city = db.Column(db.String(50))
    state = db.Column(db.String(50))

    def __repr__(self):
        return f'<Client {self.name}>'

app/models/repair.py
from app.extensions import db

class Repair(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True, nullable=False)
    price = db.Column(db.Numeric(10,2))
    
    def __repr__(self):
        return f'<Repair {self.id}, Name {self.name}>'

app/models/service.py
from app.extensions import db

class Service(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True, nullable=False)
    price = db.Column(db.Numeric(10,2))
    
    id_bike = db.Column(db.Integer, db.ForeignKey('bike.id', ondelete='CASCADE'))
    id_repair = db.Column(db.Integer, db.ForeignKey('repair.id', ondelete='CASCADE'))
    
    def __repr__(self):
        return f'<Service {self.id}, {self.name}, Bike {self.id_bike}>'

app/__init__.py
from flask import Flask

from config import DevConfig, QasConfig
from app.extensions import db

def create_app(config_class=DevConfig):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Initialize Flask extensions
    db.init_app(app)

    # Blueprint Registers
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from app.register import bp as register_bp
    app.register_blueprint(register_bp, url_prefix='/registrar')

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template
from app.main import bp


@bp.route('/')
def index():
    return render_template("main/index.html")

@bp.route('/demandas')
def demands():
    return render_template("main/demands.html")

# Criar o Modal de Serviços
@bp.route('/tmpdemands')
def tmpdemands():
    return render_template("main/service_modal.html.html")

app/register/__init__.py
from flask import Blueprint

bp = Blueprint('register', __name__)

from app.register import routes

app/register/routes.py
from flask import render_template
from app.register import bp


@bp.route('/')
def index():
    return render_template('register/index.html')

@bp.route('/clientes')
def register_clients():
    return render_template('register/client.html')

@bp.route('/servicos')
def register_services():
    return render_template('register/service.html')

@bp.route('/magrelas')
def register_bikes():
    return render_template('register/bike.html')

@bp.route('/classe')
def register_bike_class():
    return render_template('register/class.html')

@bp.route('/produtos')
def register_product():
    return render_template('register/product.html')

@bp.route('/tipoprodutos')
def register_product_type():
    return render_template('register/product_type.html')

@bp.route('/usuarios')
def register_users():
    return render_template('register/user.html')

@bp.route('/cargos')
def register_cargos():
    return render_template('register/job.html')

app/templates/includes/auth_styles.html
<!-- Link de Estilos do Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<!-- Link de Estilos de Folha da Base -->
<link rel="stylesheet" href="/static/css/auth/auth.css">

app/templates/includes/base_styles.html
<!-- Link de Estilos do Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<!-- Link do Bootstrap Icons -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<!-- Link de Estilos de Folha da Sidebar -->
<link rel="stylesheet" href="{{ url_for('static', filename='/css/base/sidebar.css') }}"/>
<!-- Link de Estilos de Folha da Base -->
<link rel="stylesheet" href="{{ url_for('static', filename='/css/base/base.css') }}"/>

app/templates/includes/loader_wheel.html
<div class="loader"></div>

<style>
    .loader {
        /* Statement básico do pre-loader */
        position: fixed;
        top: 0;
        left: 0;
        width: 100vw;
        height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
        background: var(--bs-panel);
        transition: opacity 0.75s, visibility 0.75s;

    }

    /* Esconder o pre-loader depois do seu uso */
    .loader--hiden {
        opacity: 0;
        visibility: hidden;
    }

    /* Responsável pelas animações e formato do pre-loader */
    .loader::after {
        content: "";
        width: 100px;
        height: 100px;
        animation: loading 0.75s ease infinite;
        background: url('/static/images/includes/bike-wheel.png') no-repeat center center;
        background-size: 100%;
    }

    /* Frames do pre-loader */
    @keyframes loading {
        from {
            transform: rotate(0turn)
        }

        to {
            transform: rotate(1turn)
        }
    }
</style>

<script>
    // Mecânica que esconde o loader após o carregamento da página
    window.addEventListener("load", () => {
        const loader = document.querySelector(".loader"); // Jogando a div em uma variável pra facilitar

        loader.classList.add("loader--hiden");

        // Remover o loader do HTML depois da página ser carregada.
        loader.addEventListener("transitionend", () => {
            document.body.removeChild(loader);
        });
    });
</script>

app/templates/layouts/auth_base.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/auth.css') }}" id="login-link" />
   
    <!-- Ícone -->
    <link rel="shortcut icon" href="/static/icons/tavellas-bike.svg" type="image/x-icon">

    <title>{% block title %}{% endblock %}</title>
    {% include 'includes/auth_styles.html' %}
</head>

<body>
    {% include 'includes/loader_wheel.html' %}

    <!-- Container Principal -->
    <div class="container d-flex justify-content-center align-items-center min-vh-100">
        <!-- Container de Login -->
        <div class="row rounded-5 p-0 shadow box-area">
            <!-- Caixa de Alinhamento -->
            <div class="wrapper d-flex align-items-center justify-content-center">
                <!-- Caixa da Esquerda -->
                <div class="col-md-3 rounded-4 d-flex flex-column justify-content-center align-items-center position-relative"
                    id="image-left" style="background-image: url('/static/images/auth/{{ inspiration_image }}.jpg');">
                    
                    <div class="d-flex flex-column align-items-center justify-content-center">
                        <p id="left-quote">{% block quote %}{% endblock %}<p>
                        <small id="left-quote" style="font-style: italic;">{% block author %}{% endblock %}</small>
                    </div>

                    <div class="mb-4 position-absolute bottom-0">
                        <img src="/static/images/tavellas.png" alt="Logotipo do Tavella's">
                    </div>

                </div>
                <!-- Caixa da Direita -->
                <div class="col-md-7 right-box">

                    <div class="row align-items-center">
                        <div class="header-text mb-4">
                            {% block content %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</body>

</html>

app/templates/layouts/base.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Ícone -->
    <link rel="shortcut icon" href="/static/icons/tavellas-bike.svg" type="image/x-icon">

    <!-- Link de Estilos da Base -->
    {% include 'includes/base_styles.html' %}
    {% block link %}{% endblock %}

    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <!-- Include do Pre Loader -->
    {% include 'includes/loader_wheel.html' %}

    <div class="sidebar close">
        <div class="logo-details">
            <i><img src="{{ url_for('static', filename='icons/tavellas-bike.svg') }}" alt="Ícone de Sidebar"></i>
            <span class="logo_name" style="user-select: none;">Tave<span>ll</span>a<span>'</span>s</span>
        </div>
        <ul class="nav-links">
            <li>
                <a href="#">
                    <i><img src="{{ url_for('static', filename='icons/sidebar/painel.svg') }}"
                            alt="Ícone de Sidebar"></i>
                    <span class="link_name">Painel</span>
                </a>
                <ul class="sub-menu blank">
                    <li><a class="link_name" href="">Painel</a></li>
                </ul>
            </li>

            <li>
                <a href="#">
                    <i><img src="{{ url_for('static', filename='icons/sidebar/demandas.svg') }}"
                            alt="Ícone de Sidebar"></i>
                    <span class="link_name">Demandas</span>
                </a>
                <ul class="sub-menu blank">
                    <li><a class="link_name" href="#">Demandas</a></li>
                </ul>
            </li>

            <li>
                <div class="icon-link">
                    <a href="{{ url_for('register.index') }}">
                        <i><img src="{{ url_for('static', filename='icons/sidebar/cadastrar.svg')}}"
                                alt="Ícone de Sidebar"></i>
                        <span class="link_name">Adicionar</span>
                    </a>
                    <i class='bi bi-caret-down-fill arrow'></i>
                </div>
                <ul class="sub-menu">
                    <li><a class="link_name" href="{{ url_for('register.index') }}">Adicionar</a></li>
                    <li><a href="#">Magrelas</a></li>
                    <li><a href="#">Serviços</a></li>
                    <li><a href="#">Clientes</a></li>
                </ul>
            </li>

            <li>
                <div class="icon-link">
                    <a href="#">
                        <i><img src="{{ url_for('static', filename='icons/sidebar/usuarios.svg') }}"
                                alt="Ícone de Sidebar"></i>
                        <span class="link_name">Usuários</span>
                    </a>
                    <i class='bi bi-caret-down-fill arrow'></i>
                </div>
                <ul class="sub-menu">
                    <li><a class="link_name" href="#">Usuários</a></li>
                    <li><a href="#">Cadastrar</a></li>
                    <li><a href="#">Cargos</a></li>
                </ul>
            </li>


            <li>
                <div class="icon-link">
                    <a href="#">
                        <i><img src="{{ url_for('static', filename='icons/sidebar/estoque.svg')}}"
                                alt="Ícone de Sidebar"></i>
                        <span class="link_name">Estoque</span>
                    </a>
                    <i class='bi bi-caret-down-fill arrow'></i>
                </div>
                <ul class="sub-menu">
                    <li><a class="link_name" href="#">Estoque</a></li>
                    <li><a href="#">Cadastrar</a></li>
                    <li><a href="#">Tipos</a></li>
                </ul>
            </li>

            <li>
                <a href="#">
                    <i><img src="{{ url_for('static', filename='icons/sidebar/suporte.svg') }}"
                            alt="Ícone de Sidebar"></i>
                    <span class="link_name">Suporte</span>
                </a>
                <ul class="sub-menu blank">
                    <li><a class="link_name" href="#">Suporte</a></li>
                </ul>
            </li>
            <li>

                <div class="profile-details">
                    <div class="profile-content">
                        <img src="{{ url_for('static', filename='images/tmp/robson.png') }}" alt="temporario">

                    </div>
                    <div class="name-job">
                        <div class="profile_name">Robson</div>
                        <div class="job">Dono</div>
                    </div>
                    <i class="bi bi-box-arrow-right"></i>
                </div>
            </li>
        </ul>
    </div>
    
    <!-- Conteúdo das Páginas -->
    <section class="content-section">
        <div class="container-fluid pt-3">
            {% block content %}
            {% endblock %}
        </div>
    </section>

    <script src="{{ url_for('static', filename='js/base.js') }}"></script>
</body>

</html>

app/templates/layouts/service_modal.html
<!-- Modal -->
<div class="modal fade" id="servicesModal" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- Header -->
      <div class="modal-header">
        <h5 class="modal-title">Serviços Vinculados</h5>
        <button type="button" class="btn btn-close" data-dismiss="modal"></button>
      </div>
      
      <!-- Body -->
      <div class="modal-body">

        
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Serviço</th>
              <th scope="col">Preço</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">1</th>
              <td>Mark</td>
              <td>Otto</td>
            </tr>
            <tr>
              <th scope="row">2</th>
              <td>Thornton</td>
              <td>@fat</td>
            </tr>
            <tr>
              <th scope="row">3</th>
              <td>Larry</td>
              <td>the Bird</td>
            </tr>
          </tbody>
        </table>

      </div>

      <!-- Footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-success">+ Serviços</button>
      </div>
    </div>
  </div>
</div>

app/templates/main/demands.html
{% extends 'layouts/base.html' %}

{% block title %}Demandas{% endblock %}

{% block link %}
<link rel="stylesheet" href="{{ url_for('static', filename='/css/tables.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='/css/main/demands.css') }}" />

<!-- TMP MODAL IMPORT -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
  integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
  integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock %}


{% block content %}
<div class="page-title text-center">
  <h2>Demandas</h2>
</div>
<div class="container mt-3 d-flex justify-content-center">

  <div class="demands-box">

    <table class="table table-dark table-striped table-hover table-bordered align-middle">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Bicicleta</th>
          <th>Status</th>
          <th>Serviços</th>
          <th>Ações</th>
        </tr>
      </thead>

      <tbody>
        <!-- Joao Gomes -->
        <tr>
          <td>
            <div class="d-flex align-items-center">
              <img src="/static/images/tmp/joao.png" alt="" style="width: 45px; height: 45px" class="rounded-3" />
              <div class="ms-3">
                <p class="fw-bold mb-0">João Gomes</p>
                <p class="text-muted mb-0">(19) 99175-3149</p>
              </div>
            </div>
          </td>
          <td>
            <p class="mb-1">Mountain Vermelha</p>
            <p class="text-muted mb-0 info-id">ID: 111-7B</p>
          </td>
          <td class="text-center">
            <span class="badge badge-success rounded-pill d-inline">Pronta</span>
          </td>
          <td class="text-center">
            <button type="button" class="btn btn-primary" data-toggle="modal"
              data-target="#servicesModal">
              Launch demo modal</button>
            </td>
          <!-- <td class="text-center"><a href="">4</a></td> -->
          <td class="text-center">
            <a href="">Editar</a>
          </td>
        </tr>
        <!-- Gustavo Sousa -->
        <tr>
          <td>
            <div class="d-flex align-items-center">
              <img src="/static/images/tmp/gustavo.png" class="rounded-3" alt="" style="width: 45px; height: 45px" />
              <div class="ms-3">
                <p class="fw-bold mb-0">Gustavo Sousa</p>
                <p class="text-muted mb-0">(19) 93464-3549</p>
              </div>
            </div>
          </td>
          <td>
            <p class="fw-normal mb-1">Speed Azul</p>
            <p class="text-muted mb-0 info-id">ID: 195-9C</p>
          </td>
          <td class="text-center">
            <span class="badge badge-primary rounded-pill d-inline">Aguardando</span>
          </td>
          <td class="text-center">19</td>
          <td class="text-center">
            <a href="">Editar</a>
          </td>
        </tr>

      </tbody>
    </table>

  </div>

</div>

{% include 'layouts/service_modal.html' %}

{% endblock %}

app/templates/main/index.html
{% extends 'layouts/base.html' %}

{% block title %}Home{% endblock %}

{% block link %}
<link rel="stylesheet" href="{{ url_for('static', filename='/css/main/home.css') }}"/>
{% endblock %}

{% block content %}
<!-- Container -->
<div class="container">

    <!-- Título do Header -->
    <div class="page-titles">
        <h4>Painel Inicial</h4>
        <p>Qual leão vamos matar hoje?</p>
    </div>

    <div class="row">
        <!-- Caixa do Header -->
        <div class="col-12 header-box mb-3">

            <!-- Informações Textuais -->
            <div class="row">
                <div class="col-12">
                    <p class="header-title">Outubro</p>
                    <h3 class="header-text">Evite que mais placas dessa apareçam...</h3>
                    <h5 class="header-text">Veja quais são as <strong>suas demandas</strong> do dia!</h5>
                </div>
            </div>

            <!-- Indicadores do Mês -->
            <div class="row">
                <div class="col-12 indicators">

                    <!-- Bikes Consertadas -->
                    <div class="indicator">
                        <img src="{{ url_for('static', filename='icons/home_page/header/bikes_consertadas.svg') }}">
                        <div>
                            <p>Bikes consertadas:</p>
                            <h3>21</h3>
                        </div>
                    </div>

                    <!-- Bikes Aguardando -->
                    <div class="indicator">
                        <img src="{{ url_for('static', filename='icons/home_page/header/bikes_aguardando.svg') }}">
                        <div>
                            <p>Bikes aguardando:</p>
                            <h3>21</h3>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <!-- Título do Quintal de Botões -->
    <div class="page-titles">
        <h4>Atalhos</h4>
        <p>Mais agilidade no dia a dia.</p>
    </div>

    <!-- Botões de Atalho -->
    <div class="row buttons-grid">

        <!-- Botão 1 -->
        <a href="{{ url_for('register.register_bikes')}}" class="button anchor1">
            <img src="{{ url_for('static', filename='icons/home_page/buttons/bike.svg') }}">
            <div class="button-info">
                <h5>Nova Bike</h5>
                <h2>129</h2>
            </div>
        </a>

        <!-- Botão 2 -->
        <a href="{{ url_for('register.register_clients')}}" class="button anchor2">
            <img src="{{ url_for('static', filename='icons/home_page/buttons/client.svg') }}">
            <div class="button-info">
                <h5>Novo Cliente</h5>
                <h2>129</h2>
            </div>
        </a>

        <!-- Botão 3 -->
        <div class="button anchor3">
            <h4>Relatórios</h4>
            <div class="button-info">
                <ol class="button-list">

                    <a href="">
                        <li class="button-list-item">
                            <img src="{{ url_for('static', filename='icons/home_page/buttons/report.svg') }}">
                            Fev/23
                        </li>
                    </a>

                    <a href="">
                        <li class="button-list-item">
                            <img src="{{ url_for('static', filename='icons/home_page/buttons/report.svg') }}">
                            Abr/23
                        </li>
                    </a>

                    <a href="">
                        <li class="button-list-item">
                            <img src="{{ url_for('static', filename='icons/home_page/buttons/report.svg') }}">
                            Mai/23
                        </li>
                    </a>

                    <a href="">
                        <li class="button-list-item button-list-more">
                            <img src="{{ url_for('static', filename='icons/home_page/buttons/more.svg') }}"></span>
                        </li>
                    </a>
                </ol>
            </div>
        </div>

        <!-- Botão 4 -->
        <a href="{{ url_for('register.register_product')}}" class="button anchor4" href="">
            <img src="{{ url_for('static', filename='icons/home_page/buttons/product.svg') }}">
            <div class="button-info">
                <h5>Novo Produto</h5>
                <h2>129</h2>
            </div>
        </a>

        <!-- Botão 5 -->
        <a href="{{ url_for('register.register_users')}}" class="button anchor5">
            <img src="{{ url_for('static', filename='icons/home_page/buttons/user.svg') }}">
            <div class="button-info">
                <h5>Novo Usuário</h5>
                <h2>29</h2>
            </div>
        </a>

        <!-- Botão 6 -->
        <div href="" class="button anchor6">
            <h4>Demandas</h4>
            <div class="button-info">
                <ol class="button-list">
                    <a href="">
                        <li class="button-list-item">
                            Prioridade 1
                        </li>
                    </a>
                    <a href="">
                        <li class="button-list-item">
                            Prioridade 2
                        </li>
                    </a>
                    <a href="">
                        <li class="button-list-item">
                            Prioridade 3
                        </li>
                    </a>
                    <a href="">
                        <li class="button-list-item button-list-more">
                            <img src="{{ url_for('static', filename='icons/home_page/buttons/more.svg') }}"></span>
                        </li>
                    </a>
                </ol>
            </div>
        </div>

    </div>

</div>

{% endblock %}

app/templates/register/bike.html
{% extends 'layouts/base.html' %}
{% block title %}Registrar{% endblock %}

{% block link %}
<link rel="stylesheet" href="/static/css/register/forms.css">
{% endblock %}

{% block content %}
<div class="page-title text-center">
    <h2>Cadastrar Bikes</h2>
</div>
<div class="container mt-3 d-flex justify-content-center">
    <form class="fixed-form p-2">
        <!-- Aro -->
        <div class="form-outline mb-2">
            <label>Características</label>
            <input placeholder="Aro" min="20" max="30" type="number" id="typeNumber"
                class="form-control bg-dark text-white border-0 shadow-none bold-placeholder" />
        </div>

        <!-- Quadro -->
        <div class="form-outline mb-2">
            <input placeholder="Quadro" min="12" max="21" type="number" id="typeNumber"
                class="form-control bg-dark text-white border-0 shadow-none bold-placeholder" />
        </div>

        <!-- Cor da Bike -->
        <div class="form-outline mb-2">
            <label for="colorPicker">Selecione uma cor: </label>
            <input type="color" id="colorPicker" value="#563d7c"
                class="form-control bg-dark border-0 shadow-none w-100" />
        </div>

        <!-- Modelo -->
        <div class="form-outline mb-1">
            <label>Aparência</label>
            <select class="form-select bg-dark text-white border-0 shadow-none" aria-label="Modelo">
                <option value="" disabled selected>Modelo</option>
                <option value="1">Mountain (Cadastrado previamente em Modelos)</option>
                <option value="2">Speed (Cadastrado previamente em Modelos)</option>
            </select>
            <label class="float-end gray-label">Lembre-se de <a href="#">criar um modelo</a> antes.</label>
        </div>

        <!-- Situação -->
        <div class="form-outline mb-2">
            <label>Estado da Bike</label>
            <select class="form-select bg-dark text-white border-0 shadow-none" aria-label="Estado da Bike">
                <option value="" disabled selected>Estado</option>
                <option value="1">Precária</option>
                <option value="2">Razoável</option>
            </select>
        </div>

        <!-- Condição -->
        <div class="form-outline mb-2">
            <label>Condição da Bike</label>
            <select class="form-select bg-dark text-white border-0 shadow-none" aria-label="Condição">
                <option value="" disabled selected>Condição</option>
                <option value="1">Usada</option>
                <option value="2">Nova</option>
            </select>
        </div>

        <label class="gray-label">Lembre-se de <span class="yellow-text">anotar o número da bike</span> no cartão do
            cliente.</label>

        <!-- Botão de Cadastro -->
        <div class="d-flex flex-row mt-1">
            <div>
                <button type="submit" class="btn btn-success btn-block mr-1">Cadastrar</button>
                <button type="reset" class="btn btn-danger btn-block">Cancelar</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

app/templates/register/class.html
{% extends 'layouts/base.html' %}
{% block title %}Registrar{% endblock %}

{% block link %}
<link rel="stylesheet" href="/static/css/register/forms.css">
{% endblock %}

{% block content %}
<div class="page-title text-center">
    <h2>Cadastrar Classe de Bikes</h2>
</div>
<div class="container mt-3 d-flex justify-content-center">
    <form class="fixed-form p-2">
        <!-- Nome -->
        <div class="form-outline mb-2">
            <label>Informações básicas</label>
            <input type="text" placeholder="Classe de Bike *"
                class="form-control bg-dark text-white border-0 shadow-none bold-placeholder" />
                <label class="text-end float-end gray-label ms-5 mb-1">Você está cadastrando a classe de bike <span
                        class="yellow-text">5</span>.</label>
            </div>
            
            <!-- Botão de Cadastro -->
            <div>
                <button type="submit" class="btn btn-success btn-sm mr-1">Cadastrar</button>
                <button type="reset" class="btn btn-danger btn-sm">Cancelar</button>
        </div>

    </form>
</div>

{% endblock %}

app/templates/register/job.html
{% extends 'layouts/base.html' %}
{% block title %}Registrar{% endblock %}

{% block link %}
<link rel="stylesheet" href="/static/css/register/forms.css">
{% endblock %}

{% block content %}
<div class="page-title text-center">
    <h2>Cadastrar Cargos</h2>
</div>
<div class="container mt-3 d-flex justify-content-center">
    <form class="fixed-form p-2">
        <!-- Nome do Produto -->
        <div class="form-outline mb-2">
            <label>Informações auu básicaus</label>
            <input type="text" placeholder="Au au Cargo auuu *"
                class="form-control bg-dark text-white border-0 shadow-none bold-placeholder" />
        </div>

        <!-- Nível do Cargo -->
        <div class="form-outline mb-2">
            <select class="form-select bg-dark text-white border-0 shadow-none" aria-label="Nível">
                <option value="" disabled selected>Nível do Cargo</option>
                <option value="1">Básico</option>
                <option value="2">Supremo</option>
            </select>
        </div>

        <label class="text-end float-end gray-label">Você está cadastrando o au cargo au <span class="yellow-text">5</span>.</label>

        <!-- Botão de Cadastro -->
        <div class="d-flex flex-row mt-1">
            <div>
                <button type="submit" class="btn btn-success btn-block mr-1">Cadastrar</button>
                <button type="reset" class="btn btn-danger btn-block">Cancelar</button>
            </div>
        </div>

    </form>
</div>

{% endblock %}